# Generated by Django 3.1.4 on 2023-12-01 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('color', models.CharField(max_length=200, null=True, unique=True, verbose_name='Цвет')),
                ('slug', models.SlugField(max_length=200, null=True, unique=True, verbose_name='Слаг')),
            ],
        ),
    ]
